language: generic # setting language to C will override cross-compiler and fail

sudo: required
dist: trusty

env:
  global:
    - ZEPHYR_GCC_VARIANT=zephyr
    - ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
    - ZEPHYR_BASE=$TRAVIS_BUILD_DIR/deps/zephyr
    - ZEPHYR_SDK_VERSION=0.8.2
    - ZEPHYR_SDK_DOWNLOAD_FOLDER=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/$ZEPHYR_SDK_VERSION-i686
    - ZEPHYR_SDK_SETUP_BINARY=zephyr-sdk-$ZEPHYR_SDK_VERSION-i686-setup.run
    - ZEPHYR_SDK_DOWNLOAD_URL=$ZEPHYR_SDK_DOWNLOAD_FOLDER/$ZEPHYR_SDK_SETUP_BINARY
  matrix:
    - TARGET="zephyr"
    - TARGET="zephyr-large" PARTSIZE=256
    - TARGET="BOARD=frdm_k64f"
    - TARGET="arc"
    - TARGET="linux"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install make gcc g++ python3-ply ncurses-dev uglifyjs sysvbanner -qq

install: >
  if [ "$TARGET" != "linux" ]; then
    wget $ZEPHYR_SDK_DOWNLOAD_URL &&
    chmod +x $ZEPHYR_SDK_SETUP_BINARY &&
    ./$ZEPHYR_SDK_SETUP_BINARY --quiet -- -y -d $ZEPHYR_SDK_INSTALL_DIR > /dev/null;
  fi

before_script: >
  if [ "$TARGET" != "linux" ]; then
    source zjs-env.sh $PARTSIZE &&
    make update &&
    source deps/zephyr/zephyr-env.sh
  else
    source zjs-env.sh
  fi

script: >
  if [ "$TARGET" == "zephyr" ]; then
    banner "Test 1" &&
    make V=1 &&
    banner "Test 2" &&
    make V=1 JS=samples/TrafficLight.js &&
    banner "Test 3" &&
    make V=1 JS=samples/I2C.js
  elif [ "$TARGET" == "zephyr-large" ]; then
    make V=1 JS=samples/WebBluetoothGroveLcdDemo.js
  else
    make V=1 $TARGET;
  fi
